/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Registro;

/**
 *
 * @author PaulaJCh
 */

public class GUI_Botones extends javax.swing.JPanel {
   

    /**
     * Creates new form GUI_Botones
     */
    Controlador_FRM_Registro controlador;
    public GUI_Botones() {
        initComponents();
    }
    
     public void agregarEventos(Controlador_FRM_Registro controlador)
    {
     this.controlador= controlador; 
     this.bnt_Consultar.addActionListener(controlador);
     this.bnt_Agregar.addActionListener(controlador);
     this.bnt_Modificar.addActionListener(controlador);
     this.bnt_Eliminar.addActionListener(controlador);
    }
    
    public void estadoInicial()
    {
        this.bnt_Consultar.setEnabled(true);
        this.bnt_Agregar.setEnabled(false);
        this.bnt_Eliminar.setEnabled(false);
        this.bnt_Modificar.setEnabled(false);
    }
    public void habilitarAgregar()
     {
        this.bnt_Consultar.setEnabled(false);
        this.bnt_Agregar.setEnabled(true);
        this.bnt_Eliminar.setEnabled(false);
        this.bnt_Modificar.setEnabled(false);
     }
     public void habilitarOpciones()
     {
        this.bnt_Consultar.setEnabled(false);
        this.bnt_Agregar.setEnabled(false);
        this.bnt_Eliminar.setEnabled(true);
        this.bnt_Modificar.setEnabled(true);
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bnt_Consultar = new javax.swing.JButton();
        bnt_Agregar = new javax.swing.JButton();
        bnt_Modificar = new javax.swing.JButton();
        bnt_Eliminar = new javax.swing.JButton();

        bnt_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        bnt_Consultar.setActionCommand("Consultar");

        bnt_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        bnt_Agregar.setActionCommand("Agregar");

        bnt_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        bnt_Modificar.setActionCommand("Modificar");

        bnt_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        bnt_Eliminar.setActionCommand("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnt_Consultar)
                .addGap(18, 18, 18)
                .addComponent(bnt_Agregar)
                .addGap(18, 18, 18)
                .addComponent(bnt_Modificar)
                .addGap(18, 18, 18)
                .addComponent(bnt_Eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_Consultar)
                    .addComponent(bnt_Agregar)
                    .addComponent(bnt_Modificar)
                    .addComponent(bnt_Eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Agregar;
    private javax.swing.JButton bnt_Consultar;
    private javax.swing.JButton bnt_Eliminar;
    private javax.swing.JButton bnt_Modificar;
    // End of variables declaration//GEN-END:variables
}